name: Sync Codex Changes

on:
  push:
    branches:
      - main

jobs:
  auto-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "Codex Sync Bot"
          git config user.email "codex-bot@example.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-sync: cambios desde Codex" || echo "No hay cambios que sincronizar"
          git push origin main
